// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdINe-bz_eSRp4_N5HyRYzNemtrcBYfyQ',
    appId: '1:402582001978:web:a3f939b936c7e348221803',
    messagingSenderId: '402582001978',
    projectId: 'bharat-doorstep-native',
    authDomain: 'bharat-doorstep-native.firebaseapp.com',
    databaseURL: 'https://bharat-doorstep-native-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bharat-doorstep-native.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyYG4JXt2rYPpycGKso1-Ew0ST9HY6oaw',
    appId: '1:402582001978:android:15d263e51ee79e5f221803',
    messagingSenderId: '402582001978',
    projectId: 'bharat-doorstep-native',
    databaseURL: 'https://bharat-doorstep-native-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bharat-doorstep-native.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDY3UHiNauZTimqYdNKynBoChJtTXL4uUk',
    appId: '1:402582001978:ios:66ae8cd80d7cf1d0221803',
    messagingSenderId: '402582001978',
    projectId: 'bharat-doorstep-native',
    databaseURL: 'https://bharat-doorstep-native-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bharat-doorstep-native.firebasestorage.app',
    iosBundleId: 'com.example.bharatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDY3UHiNauZTimqYdNKynBoChJtTXL4uUk',
    appId: '1:402582001978:ios:66ae8cd80d7cf1d0221803',
    messagingSenderId: '402582001978',
    projectId: 'bharat-doorstep-native',
    databaseURL: 'https://bharat-doorstep-native-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bharat-doorstep-native.firebasestorage.app',
    iosBundleId: 'com.example.bharatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdINe-bz_eSRp4_N5HyRYzNemtrcBYfyQ',
    appId: '1:402582001978:web:d80dcf4722da4d7e221803',
    messagingSenderId: '402582001978',
    projectId: 'bharat-doorstep-native',
    authDomain: 'bharat-doorstep-native.firebaseapp.com',
    databaseURL: 'https://bharat-doorstep-native-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bharat-doorstep-native.firebasestorage.app',
  );
}
